import Head from 'next/head'

// components
import Layout from '@/components/Layout'

// sections
import Hero from '@/components/Hero'

export default function Home() {
	return (
		<>
			<Head>
				<title>Parallel CRE</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<Hero />
			</Layout>
		</>
	)
}
