import Head from 'next/head'

// components
import Layout from '@/components/Layout'

export default function Home() {
	return (
		<>
			<Head>
				<title>Parallel CRE</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<div
					className='containerCenter'
					style={{ 'height': '3000px', 'marginTop': '150px' }}
				>
					<p>Parallel CRE</p>
				</div>
			</Layout>
		</>
	)
}
